version: '3.8'

services:
  builder:
    image: flutter-sample-builder
    build: .
    environment:
      - REPO_URL=git@github.com:test/test.git
      # - REPO_BRANCH=master
      - SSH_KEY=/root/ssh_key
      # - COMMIT_SHA=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
      # - LOCAL_BUILD=1 # Use volume instead of pulling repo
      # - DIRTY_BUILD=1 # Do not run flutter clean
      # - VERBOSE=1
    volumes:
      # - ./repo:/root/repo:rw
      - ./apk:/root/apk:rw
      - ./ssh_key:/root/ssh_key:ro
